# Generated by Django 3.2.16 on 2024-02-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='老板')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('img', models.CharField(max_length=64, verbose_name='图片')),
            ],
        ),
    ]
